/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in local projects.
// It is committed here so the initial scaffold can typecheck in a fresh clone.
